---
- name: Check if runner is already installed
  stat: path=/usr/bin/gitlab-runner
  register: runner_file

- name: Create runner directories
  file:
    path: "{{ runner_install_dir }}/{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - metadata
    - builds
    - cache
    - fargate
  when: not runner_file.stat.exists

- name: Download GitLab repository installation script
  get_url:
    url: "{{ gitlab_repository_installation_script_url }}"
    dest: /tmp/gitlab_install_repository.sh
    validate_certs: "{{ gitlab_download_validate_certs }}"
  when: not runner_file.stat.exists

- name: Install GitLab repository
  command: bash /tmp/gitlab_install_repository.sh
  register: output
  when: not runner_file.stat.exists

- name: Install runner
  package:
    name: gitlab-runner
    state: present
  async: 300
  poll: 5
  when: not runner_file.stat.exists

- name: Copy Fargate config
  template:
    src: fargate.toml.j2
    dest: "{{ runner_install_dir }}/fargate/config.toml"
    mode: '0644'

# - name: Register runner
#   command: "gitlab-runner register --url {{ gitlab_external_url }} --registration-token {{ runner_registration_token }} --name fargate-test-runner --run-untagged --executor custom -n"
#   when: not runner_file.stat.exists

- name: Register runner
  command: "curl -X POST \"{{ gitlab_external_url }}/api/v4/runners\" -F \"token={{ runner_registration_token }}\" -F \"description={{ runner_name }}\""
  when: not runner_file.stat.exists
  register: registration_result

- name: Set variables from registration result
  set_fact:
    runner_id: "{{ registration_result.stdout | from_json | json_query('id') }}"
    runner_auth_token: "{{ registration_result.stdout | from_json | json_query('token') }}"    

- name: Copy runner config
  template:
    src: config.toml.j2
    dest: "{{ runner_install_dir }}/config.toml"
    mode: '0644'

- name: Install Fargate driver
  get_url:
    url: https://gitlab-runner-custom-fargate-downloads.s3.amazonaws.com/latest/fargate-linux-amd64
    dest: "{{ runner_install_dir }}/fargate/fargate"
    mode: '0755'

# Forces an initial connection from the runner to the server
- name: Verify that the runner can connect to the server
  command: "gitlab-runner verify"
  when: not runner_file.stat.exists