---
- hosts: gitlab
  become: true
  vars_files:
    - vars/main.yml
  roles:
    - { role: geerlingguy.gitlab }

- hosts: runner
  become: true
  vars_files:
    - vars/main.yml
  roles:
    - runner